---

name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8]
        ci_pattern:
          - test_query.py
          - test_add_target.py
          - test_authorization_header.py
          - test_content_length.py
          - test_database_summary.py
          - test_date_header.py::TestFormat
          - test_date_header.py::TestMissing
          - test_date_header.py::TestSkewedTime
          - test_delete_target.py
          - test_get_duplicates.py
          - test_get_target.py
          - test_invalid_given_id.py
          - test_invalid_json.py
          - test_target_list.py
          - test_target_summary.py
          - test_unexpected_json.py
          - test_update_target.py::TestActiveFlag
          - test_update_target.py::TestApplicationMetadata
          - test_update_target.py::TestImage
          - test_update_target.py::TestTargetName
          - test_update_target.py::TestUnexpectedData
          - test_update_target.py::TestUpdate
          - test_update_target.py::TestWidth
          - test_update_target.py::TestInactiveProject
          - test_usage.py

    steps:
      - uses: actions/checkout@v2
      - name: "Set up Python"
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: "Install dependencies"
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade --editable .[dev]

      - name: "Set secrets file"
        run: |
          # See the "CI Setup" document for details of how this was set up.
          openssl aes-256-cbc -K $encrypted_61e4bc3d8ae5_key -iv $encrypted_61e4bc3d8ae5_iv -in secrets.tar.enc -out secrets.tar -d
          tar xvf secrets.tar
          python ci/set_secrets_file.py
        env:
          CI_PATTERN: ${{ matrix.ci_pattern }}

      # - name: "Run tests"
      #   run: |
      #     pytest -s -vvv --cov=src/ --cov=tests --cov-report=xml tests/mock_vws/${{ matrix.ci_pattern }}
      #
      # - name: "Upload coverage to Codecov"
      #   uses: "codecov/codecov-action@v1"
      #   with:
      #     fail_ci_if_error: true
